; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:airm2m_core_esp32c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    ; Arduino USB configuration
    ; -DARDUINO_USB_MODE=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    ; E-Ink display resolution (SSD1680 2.13" panel)
    -DEPD_WIDTH=122
    -DEPD_HEIGHT=250
    ; SPI pin definitions
    -DHW_SCK=2
    -DHW_MOSI=3
    -DHW_MISO=-1
    ; E-Paper display control pins
    -DPIN_CS=7
    -DPIN_DC=6
    -DPIN_RST=10
    -DPIN_BUSY=5

lib_deps =
    adafruit/Adafruit GFX Library
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    ArduinoJson
    GxEPD2
    OneButton
    olikraus/U8g2_for_Adafruit_GFX
; File system configuration
; Size for LittleFS partition (bytes)
board_build.partitions = partitions.csv
